routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home.welcome');
});

Route::get('/admin', function () {
    return redirect()->route('admin.home');
});

Route::get('/timecheck', function () {
    return now()->format('d m y, h:m:s');
});

Route::group(['prefix' => 'admin',], function () {

    Auth::routes();

    Route::middleware(['auth'])->group(function () {

        Route::get('/dashboard', 'HomeController@index')->name('admin.home');

        Route::group(['prefix' => 'students'],  function () {

            Route::resource('logs', StudentLogController::class);

            Route::post('/profiles/import', 'StudentProfileController@import')->name('profiles.import');

            Route::resource('profiles', StudentProfileController::class);

            Route::resource('violations', StudentViolationController::class);
        });

        Route::get('/analytics/cluster', 'AnalyticsController@cluster')->name('analytics.cluster');

        Route::resource('/analytics', AnalyticsController::class);

        Route::group(['prefix' => 'violations'], function () {

            Route::get('/', 'ViolationsController@index')->name('violations');

            Route::get('/all/{order?}', 'ViolationsController@all')->name('violations.all');

            Route::post('/create', 'ViolationsController@create')->name('violations.create');

            Route::get('/edit/{id}', 'ViolationsController@showEdit')->name('violations.edit');

            Route::post('/edit/{id}', 'ViolationsController@edit');

            Route::get('/get/{id}', 'ViolationsController@get')->name('violations.get');

            Route::post('/import', 'ViolationsController@import')->name('violations.import');
        });

        Route::group(['prefix' => 'reports'], function () {

            Route::get('/violations', 'ReportController@index')->name('reports.violations');

            Route::get('/logs', 'ReportController@index')->name('reports.logs');

            Route::get('/logs/get', 'ReportController@getLogsReport')->name('reports.logs.get');

            Route::get('/violations/get', 'ReportController@getViolationReport')->name('reports.violations.get');
        });

        Route::group(['prefix' => 'colleges'], function () {

            Route::get('/', 'CollegesController@index')->name('colleges');

            Route::get('/course/{code}', 'CollegesController@course')->name('colleges.course');

            Route::post('/import/college', 'CollegesController@importCollege')->name('colleges.import.college');

            Route::post('/import/course', 'CollegesController@importCourse')->name('colleges.import.course');

            Route::get('/all', 'CollegesController@all')->name('colleges.all');

            Route::get('/get/course/{code}', 'CollegesController@getCourse')->name('colleges.get.course');
        });

        Route::group(['prefix' => 'globe'], function () {

            Route::post('/send', 'GlobeController@sendSMS')->name('globe.send');
        });

        Route::group(['prefix' => 'test'], function () {

            Route::get('/', 'TestController@index')->name('test');

            Route::get('/csrf', 'TestController@showToken')->name('test.csrf');

            Route::get('/truncate', 'TestController@truncate')->name('test.truncate');
        });

        Route::group(['prefix' => 'announcement'], function () {

            Route::get('/', 'AnnouncementController@index')->name('announcement');

            Route::post('/send', 'AnnouncementController@send')->name('announcement.send');
        });
    });
});

app/Violations.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Violations extends Model
{
    protected $table = 'violations';

    protected $fillable = [
        'id',
        'title',
        'type',
        'first_offense',
        'second_offense',
        'third_offense',
    ];

    protected $hidden = ['created_at', 'updated_at'];

    public function getFirstOffenseAttribute($value)
    {
        return $value;
    }
}

app/Http/Controllers/ViolationsController.php
<?php

namespace App\Http\Controllers;

use App\Violations;
use Illuminate\Http\Request;

class ViolationsController extends Controller
{
    public function index()
    {
        return view('violations.violations_index');
    }

    public function create(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'type' => 'required',
            'first_offense' => 'required'
        ]);

        if (Violations::create($request->all())) {
            return $this->success('Violation Added');
        } else {
            return $this->reject('Violation Failed');
        }
    }

    public function showEdit($id)
    {
        $violation = Violations::find($id);
        return view('violations.violations_edit', ['violation' => $violation]);
    }

    public function edit($id, Request $request)
    {
        $request->validate([
            'title' => 'required',
            'type' => 'required',
            'first_offense' => 'required'
        ]);

        $violation = Violations::find($id)->update($request->except('_token'));

        if ($violation) {
            return redirect()->route('violations')->with(['message' => 'Violation Updated', 'class' => 'success']);
        } else {
            return redirect()->route('violations')->with(['message' => 'Violation Updated Failed', 'class' => 'success']);
        }
    }

    public function all($order = 'type')
    {
        return  Violations::orderBy($order)->get();
    }

    public function get($id)
    {
        $violation = Violations::find($id);
        $data = [
            $violation['first_offense'],
            $violation['second_offense'],
            $violation['third_offense'],
        ];
        return $data;
    }

    public function import(Request $request)
    {
        if ($request->hasFile('file')) {
            $data = json_decode(file_get_contents($request->file), true);
            foreach ($data as $violation) {
                Violations::create($violation);
            }
            return redirect()->route('violations')->with(['message' => 'Import Success', 'class' => 'success']);
        }
        return redirect()->route('violations')->with(['message' => 'File Not Found', 'class' => 'error']);
    }
}

resources/views/students/violations/violations_create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Students / Create</h6>
            </div>
            <div class="card-body">
                <form method="post">
                    @csrf
                    <div class="form-group">
                        <label for="id_number">ID Number</label>
                        <input type="text" name="id_number" id="id_number"
                            class="form-control @error('id_number') is-invalid @enderror" value="{{old('id_number')}}">
                        <small>For new violation only.</small>
                        @error('id_number')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="violation_id">Violation</label>
                        <select name="violation_id" id="violation_id" class="form-control">
                            @foreach ($violations as $violation)
                            <option value="{{$violation->id}}"
                                {{old('violation_id') == $violation->id?'selected':null}}>
                                {{$violation->title}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="text-center">
                        <button class="btn btn-warning"><i class="fas fa-save"></i> Register Violation to
                            Student</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<script>
    $(document).ready(function () {

    });
</script>
@endsection

resources/views/students/violations/violations_index.blade.php
@extends('layouts.admin')

@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Students / Violations </h6>
    </div>
    <div class="card-body ">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-sm nowrap" style="width: 100%" id="table">
                    <thead></thead>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

@section('js')
<script>
    $(document).ready(function () {
        let table = $('#table').DataTable({
            scrollX: true,
            "autoWidth": false,
            ajax: {
                url: "/api/violations/all",
                dataSrc: ''
            }, 
            columns: [
                {data: 'id_number', title: 'ID Number'},
                {data: 'title', title: 'Violation'},
                {data: null, title: 'Sanction', render: (d) => {
                    // console.log(d.type);
                        if(d['type'] == "Minor") {
                            return `<p class="badge badge-pill badge-warning">${d.sanction}</p>`;
                        }else{
                            return `<p class="badge badge-pill badge-danger">${d.sanction}</p>`;
                        }
                    }
                },
                {data: 'expired_at', title: 'Expiry Date'},
                {data: 'status', title: 'Status',
                    render: (d) => {
                        if(d == "pending") {
                            return `<p class="badge badge-pill badge-warning">${d}</p>`;
                        }else{
                            return `<p class="badge badge-pill badge-success">${d}</p>`;
                        }
                    }
                },
                {data: 'cleared_at', title: 'Cleared Date'},

            ],
            dom: 'Bfrtip',
            buttons: [
                {
                    text: '<i class="fas fa-file-csv"></i> Save as CSV',
                    extend: 'csv',
                    className: 'btn btn-success mx-1 rounded-pill',
                    title: 'Report List'
                },
                {
                    text: '<i class="fas fa-file-pdf"></i> Save as PDF',
                    extend: 'pdf',
                    className: 'btn btn-success mx-1 rounded-pill',
                    title: 'Report List'
                },
            ]
        });
    });
</script>
@endsection

resources/views/students/violations/violations_show.blade.php
@extends('layouts.admin')

@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Students / <a href="{{ route('violations.index') }}">Violations</a> / {{$id_number}} </h6>
    </div>
    <div class="card-body ">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-sm nowrap" style="width: 100%" id="table">
                    <thead></thead>
                </table>
            </div>
        </div>
    </div>
</div>

{{-- Violation create modal --}}
@include('students.violations.modals.violation_create_modal')

{{-- Violation clearance modal --}}
@include('students.violations.modals.violation_clearance_modal')

@endsection

@section('js')
<script>
    $('#violation_id').select2({theme: "classic"});
        var table = $('#table').DataTable({
            ajax: {
                url: "/api/violations/get/{{ $id_number }}",
                dataSrc: ''
            },
            fixedColumns: {
                leftColumns:0,
                rightColumns: 1
            },
            columns: [
                {data: 'id_number', title: 'ID Number'},
                {
                    data: 'type', title: 'Violation type', className: 'text-center',
                    render: function (data) {
                        if(data == 'Minor') {
                            return `<p class="badge badge-pill badge-warning">${data}</p>`;
                        } else{
                            return `<p class="badge badge-pill badge-danger">${data}</p>`;
                        }
                    }
                },
                {data: 'title', title: 'Title'},
                {
                    data: 'sanction', title: 'Sanction', render: d => {
                        if(d == "Suspension" || d == "Expelled") {
                            return `<p class="badge badge-danger badge-pill rounded-pill">${d}</p>`;
                        }else{
                            return `<p class="badge badge-warning badge-pill rounded-pill">${d}</p>`;
                        }
                    }
                },
                {
                    data: 'status', title: 'Violation status', render: (d) => {
                        if (d == 'pending') {
                            return `<p class="badge badge-warning rounded-pill px-3">${d}</p>`;
                        }else if (d == 'expired_at') {
                            return `<p class="badge badge-danger rounded-pill px-3">${d}</p>`;
                        } else {
                            return `<p class="badge badge-success rounded-pill px-3">${d}</p>`;
                        }
                    }
                },
                {
                    data: 'created_at', title: 'Violation Date', render: (d) => {
                        let date = moment(new Date(d)).format("MMMM DD, YYYY");
                        return `${date}`;
                    }
                },
                {
                    data: 'expired_at', title: 'Expiry Date', render: (d) => {
                        if(d != null){
                            let date = moment(new Date(d)).format("MMMM DD, YYYY");
                            return `${date}`;
                        }else{
                            return '';
                        }
                    }
                },
                {
                    data: null, name: 'action',title: 'Action', render: (d) => {
                        return d.status == 'cleared' ? '' : `<button type="button" name="clear" class="btn btn-success btn-sm mx-1" data-toggle="modal" data-target="#clearance" data-id=${d.id}> <i class="fas fa-check"></i> Clear</button>`;
                    }
                }
            ],
            dom: 'lBfrtip',
            buttons: [
                {
                    text: '<i class="fa fa-plus"></i> Add Violation',
                    className: 'btn btn-warning btn-sm rounded-pill',
                    action: function () {
                        $('#add').modal('show');
                    }
                },
            ],
            scrollX: true
        });

        $('#add').on('show.bs.modal', function (e) {
            let btn = $(e.relatedTarget);
            let id = btn.data('id-number');
            let val_id = $('#violation_id').val();
            getSanction(val_id);
        });

        $('#violation_id').change(function() {
            let id = $(this).val();
            getSanction(id);
        });

        $('#form').submit(function (e) {
            e.preventDefault();
            let data = $(this).serialize();
            let url = "{{route('violations.create', ['id_number' => ':id'])}}";
            $.ajax({
                url: url.replace(':id', id),
                type: 'post',
                data: data,
                beforeSend: function () {
                    $('#add').modal('hide');
                },
                complete: function (j, s) {
                    if(j.status >= 200 && j.status < 400) {
                        alertify.success(j.responseJSON.message)
                    }else {
                        alertify.error(j.responseJSON.message)
                    }
                    table.ajax.reload();
                }
            });
        });

        let clearance_id;
        
        $('#clearance').on('show.bs.modal', function (e) {
            clearance_id = $(e.relatedTarget).data('id');

        });

        $('#confirm_clearance').click(function(e){
            // console.log(clearance_id);
            clearViolation(clearance_id);
            $('#clearance').modal('toggle');
        });

        function clearViolation(id){
            // let id = $(e.target).data('id');
            $.ajax({
                url: "/api/violations/clear",
                type: 'post',
                data: {id: id},
                complete: (j, s) => {
                    if(j.statusText = "OK"){
                        alertify.success(j.responseJSON.message);
                    }
                    table.ajax.reload();
                }
            });
        }

        function getSanction(id) {
            $.ajax({
                url: "/api/violation/get/{{ $id_number }}",
                type: 'get',
                complete: function(j, s) {
                    $('#sanction').children().remove();
                    if(j.statusText == "OK") {
                        j.responseJSON.forEach(e => {
                            if(e){
                                $('#sanction').append($('<option>').text(e).val(e));
                            }
                        });
                    }
                }
            });
        }
</script>
@if (Auth::user()->role == 1)
<script>
    table.on('draw', function () {
        table.column(7).visible(false);
    });
</script>
@endif
@endsection

resources/views/students/violations/violations_single.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Students / Violations / {{ ucfirst($id_number)}} </h6>
            </div>
            <div class="card-body">
                <table class="table table-hover" id="table"></table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<script>
    $(document).ready(function () {
        let url = "{{route('students.violations.get', ['id_number' => ':id_number'])}}";
        let id_number = "{{$id_number}}";
        let table = $('#table').DataTable({
            ajax: {
                url: url.replace(':id_number', id_number),
                dataSrc: ''
            },
            columns: [
                {data: 'title', title: 'Title'},
                {
                    data: 'type', title: 'Type', render: function (data) {
                        if(data == "Minor") {
                            return `<p class="badge badge-pill badge-warning">${data}</p>`;
                        } else {
                            return `<p class="badge badge-pill badge-danger">${data}</p>`;
                        }
                    }
                },
                {data: 'penalty', title: 'Penalty/Sanction'},
                {data: 'expired_at', title: 'Expires Date'},
                {data: 'cleared_at', title: 'Cleared Date'},
                {
                    data: null, title: 'Action', render: function (data) {
                        return `<button type="button" class="btn btn-success btn-sm" data-id=${data.id} name="potangina"><i class="fas fa-check"></i> Clear</button>`;
                    }
                }
            ],
            dom: 'lBfrtip',
            // buttons: []
        });

        $(document).on('click', 'button[name=potangina]', function () {
            let id = $(this).data('id');
            console.log(id);
            let url = "{{route('students.violations.clear', ['id' => ':id'])}}";
            $.ajax({
                url: url.replace(':id', id),
                type: 'get',
                success: function (d, s, j) {
                    alertify.success(j.responseJSON.message);
                },
                error: function (j, s, e) {
                    console.log(j);
                },
                complete: function () {
                    table.ajax.reload();
                }
            });
        }); 
    });
</script>
@endsection