routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home.welcome');
});

Route::get('/admin', function () {
    return redirect()->route('admin.home');
});

Route::get('/timecheck', function () {
    return now()->format('d m y, h:m:s');
});

Route::group(['prefix' => 'admin',], function () {

    Auth::routes();

    Route::middleware(['auth'])->group(function () {

        Route::get('/dashboard', 'HomeController@index')->name('admin.home');

        Route::group(['prefix' => 'students'],  function () {

            Route::resource('logs', StudentLogController::class);

            Route::post('/profiles/import', 'StudentProfileController@import')->name('profiles.import');

            Route::resource('profiles', StudentProfileController::class);

            Route::resource('violations', StudentViolationController::class);
        });

        Route::get('/analytics/cluster', 'AnalyticsController@cluster')->name('analytics.cluster');

        Route::resource('/analytics', AnalyticsController::class);

        Route::group(['prefix' => 'violations'], function () {

            Route::get('/', 'ViolationsController@index')->name('violations');

            Route::get('/all/{order?}', 'ViolationsController@all')->name('violations.all');

            Route::post('/create', 'ViolationsController@create')->name('violations.create');

            Route::get('/edit/{id}', 'ViolationsController@showEdit')->name('violations.edit');

            Route::post('/edit/{id}', 'ViolationsController@edit');

            Route::get('/get/{id}', 'ViolationsController@get')->name('violations.get');

            Route::post('/import', 'ViolationsController@import')->name('violations.import');
        });

        Route::group(['prefix' => 'reports'], function () {

            Route::get('/violations', 'ReportController@index')->name('reports.violations');

            Route::get('/logs', 'ReportController@index')->name('reports.logs');

            Route::get('/logs/get', 'ReportController@getLogsReport')->name('reports.logs.get');

            Route::get('/violations/get', 'ReportController@getViolationReport')->name('reports.violations.get');
        });

        Route::group(['prefix' => 'colleges'], function () {

            Route::get('/', 'CollegesController@index')->name('colleges');

            Route::get('/course/{code}', 'CollegesController@course')->name('colleges.course');

            Route::post('/import/college', 'CollegesController@importCollege')->name('colleges.import.college');

            Route::post('/import/course', 'CollegesController@importCourse')->name('colleges.import.course');

            Route::get('/all', 'CollegesController@all')->name('colleges.all');

            Route::get('/get/course/{code}', 'CollegesController@getCourse')->name('colleges.get.course');
        });

        Route::group(['prefix' => 'globe'], function () {

            Route::post('/send', 'GlobeController@sendSMS')->name('globe.send');
        });

        Route::group(['prefix' => 'test'], function () {

            Route::get('/', 'TestController@index')->name('test');

            Route::get('/csrf', 'TestController@showToken')->name('test.csrf');

            Route::get('/truncate', 'TestController@truncate')->name('test.truncate');
        });

        Route::group(['prefix' => 'announcement'], function () {

            Route::get('/', 'AnnouncementController@index')->name('announcement');

            Route::post('/send', 'AnnouncementController@send')->name('announcement.send');
        });
    });
});

app/Violations.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Violations extends Model
{
    protected $table = 'violations';

    protected $fillable = [
        'id',
        'title',
        'type',
        'first_offense',
        'second_offense',
        'third_offense',
    ];

    protected $hidden = ['created_at', 'updated_at'];

    public function getFirstOffenseAttribute($value)
    {
        return $value;
    }
}

app/Http/Controllers/ViolationsController.php
<?php

namespace App\Http\Controllers;

use App\Violations;
use Illuminate\Http\Request;

class ViolationsController extends Controller
{
    public function index()
    {
        return view('violations.violations_index');
    }

    public function create(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'type' => 'required',
            'first_offense' => 'required'
        ]);

        if (Violations::create($request->all())) {
            return $this->success('Violation Added');
        } else {
            return $this->reject('Violation Failed');
        }
    }

    public function showEdit($id)
    {
        $violation = Violations::find($id);
        return view('violations.violations_edit', ['violation' => $violation]);
    }

    public function edit($id, Request $request)
    {
        $request->validate([
            'title' => 'required',
            'type' => 'required',
            'first_offense' => 'required'
        ]);

        $violation = Violations::find($id)->update($request->except('_token'));

        if ($violation) {
            return redirect()->route('violations')->with(['message' => 'Violation Updated', 'class' => 'success']);
        } else {
            return redirect()->route('violations')->with(['message' => 'Violation Updated Failed', 'class' => 'success']);
        }
    }

    public function all($order = 'type')
    {
        return  Violations::orderBy($order)->get();
    }

    public function get($id)
    {
        $violation = Violations::find($id);
        $data = [
            $violation['first_offense'],
            $violation['second_offense'],
            $violation['third_offense'],
        ];
        return $data;
    }

    public function import(Request $request)
    {
        if ($request->hasFile('file')) {
            $data = json_decode(file_get_contents($request->file), true);
            foreach ($data as $violation) {
                Violations::create($violation);
            }
            return redirect()->route('violations')->with(['message' => 'Import Success', 'class' => 'success']);
        }
        return redirect()->route('violations')->with(['message' => 'File Not Found', 'class' => 'error']);
    }
}

resources/views/students/violations/modals/violation_clearance_modal.blade.php
<!-- Clearance Modal -->
<div class="modal fade" id="clearance" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Clear violation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to clear the violation?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="confirm_clearance">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

resources/views/students/violations/modals/violation_create_modal.blade.php
<!-- Add violation modal -->
<div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="addModaLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addModaLabel">Add Violation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {{-- <form method="post" action="{{route('students.violations.create')}}"> --}}
            <form method="POST" id="form">
                <div class="modal-body">
                    @csrf
                    <div class="form-group">
                        <label for="id_number">ID Number</label>
                        <input type="text" name="id_number" id="id_number" value="{{$id_number}}" readonly
                            class="form-control @error('id_number') is-invalid @enderror">
                        @error('id_number')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="violation_id">Violation</label>
                        <select name="violation_id" id="violation_id" class="form-control" style="width: 100%">
                            @foreach ($violations as $violation)
                            <option value="{{$violation->id}}">{{$violation->title}}</option>
                            @endforeach
                        </select>
                        @error('violation_id')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="sanction">Sanction</label>
                        <select name="sanction" id="sanction"
                            class="form-control @error('sanction') is-invalid @enderror">
                        </select>
                        @error('sanction')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button class="btn btn-warning">
                        <i class="fas fa-save"></i> Save
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>