routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home.welcome');
});

Route::get('/admin', function () {
    return redirect()->route('admin.home');
});

Route::get('/timecheck', function () {
    return now()->format('d m y, h:m:s');
});

Route::group(['prefix' => 'admin',], function () {

    Auth::routes();

    Route::middleware(['auth'])->group(function () {

        Route::get('/dashboard', 'HomeController@index')->name('admin.home');

        Route::group(['prefix' => 'students'],  function () {

            Route::resource('logs', StudentLogController::class);

            Route::post('/profiles/import', 'StudentProfileController@import')->name('profiles.import');

            Route::resource('profiles', StudentProfileController::class);

            Route::resource('violations', StudentViolationController::class);
        });

        Route::get('/analytics/cluster', 'AnalyticsController@cluster')->name('analytics.cluster');

        Route::resource('/analytics', AnalyticsController::class);

        Route::group(['prefix' => 'violations'], function () {

            Route::get('/', 'ViolationsController@index')->name('violations');

            Route::get('/all/{order?}', 'ViolationsController@all')->name('violations.all');

            Route::post('/create', 'ViolationsController@create')->name('violations.create');

            Route::get('/edit/{id}', 'ViolationsController@showEdit')->name('violations.edit');

            Route::post('/edit/{id}', 'ViolationsController@edit');

            Route::get('/get/{id}', 'ViolationsController@get')->name('violations.get');

            Route::post('/import', 'ViolationsController@import')->name('violations.import');
        });

        Route::group(['prefix' => 'reports'], function () {

            Route::get('/violations', 'ReportController@index')->name('reports.violations');

            Route::get('/logs', 'ReportController@index')->name('reports.logs');

            Route::get('/logs/get', 'ReportController@getLogsReport')->name('reports.logs.get');

            Route::get('/violations/get', 'ReportController@getViolationReport')->name('reports.violations.get');
        });

        Route::group(['prefix' => 'colleges'], function () {

            Route::get('/', 'CollegesController@index')->name('colleges');

            Route::get('/course/{code}', 'CollegesController@course')->name('colleges.course');

            Route::post('/import/college', 'CollegesController@importCollege')->name('colleges.import.college');

            Route::post('/import/course', 'CollegesController@importCourse')->name('colleges.import.course');

            Route::get('/all', 'CollegesController@all')->name('colleges.all');

            Route::get('/get/course/{code}', 'CollegesController@getCourse')->name('colleges.get.course');
        });

        Route::group(['prefix' => 'globe'], function () {

            Route::post('/send', 'GlobeController@sendSMS')->name('globe.send');
        });

        Route::group(['prefix' => 'test'], function () {

            Route::get('/', 'TestController@index')->name('test');

            Route::get('/csrf', 'TestController@showToken')->name('test.csrf');

            Route::get('/truncate', 'TestController@truncate')->name('test.truncate');
        });

        Route::group(['prefix' => 'announcement'], function () {

            Route::get('/', 'AnnouncementController@index')->name('announcement');

            Route::post('/send', 'AnnouncementController@send')->name('announcement.send');
        });
    });
});

resources/views/students/profiles/profile_show.blade.php
@extends('layouts.admin')

@section('content')
<!-- Basic Card Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            Students / <a href="{{route('profiles.index')}}">Profile</a> / {{$profile->id_number}}
        </h6>
    </div>
    <div class="card-body">

        <div class="container py-4 my-2">
            <div class="row">
                <div class="col-md-4 pr-md-5">
                    <img class="w-100 rounded border" src="{{ asset('storage/'.$profile->profile_picture)}}"
                        alt="Profile Picture" title="{{$profile->first_name}}" />
                    <div class="pt-4 mt-2">
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="d-flex align-items-center">
                        <h2 class="font-weight-bold m-0">
                            {{$profile->first_name.' '.$profile->middle_name.' '.$profile->last_name}}
                        </h2>
                    </div>
                    <section class="mt-4">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                    aria-controls="home" aria-selected="true">
                                    About
                                </a>
                            </li>
                        </ul>
                        <div class="tab-content py-4" id="myTabContent">
                            <div class="tab-pane py-3 fade show active" id="home" role="tabpanel"
                                aria-labelledby="home-tab">
                                <h6 class="text-uppercase font-weight-light text-secondary">
                                    Contact Information
                                </h6>
                                <dl class="row mt-4 mb-4 pb-3">
                                    <dt class="col-sm-3">Phone</dt>
                                    <dd class="col-sm-9">{{$profile->contact_number}}</dd>

                                    <dt class="col-sm-3">Email address</dt>
                                    <dd class="col-sm-9">{{$profile->umak_email}}</dd>
                                </dl>

                                <h6 class="text-uppercase font-weight-light text-secondary">
                                    Educational Background
                                </h6>
                                <dl class="row mt-4 mb-4 pb-3">
                                    <dt class="col-sm-3">College</dt>
                                    <dd class="col-sm-9">{{$profile->college}}</dd>

                                    <dt class="col-sm-3">Course</dt>
                                    <dd class="col-sm-9">{{$profile->course}}</dd>
                                </dl>
                            </div>
                        </div>
                    </section>
                    <div class="center">
                        <a href="{{ route('profiles.index') }}" class="btn btn-success btn-sm">Return</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/students/profiles/profiles_create.blade.php
@extends('layouts.admin')

@section('content')
<!-- Basic Card Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Students / Create</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('profiles.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="row justify-content-center align-items-center">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="id_number">ID Number</label>
                        <input type="text" name="id_number" id="id_number"
                            class="form-control @error('id_number') is-invalid @enderror" value="{{old('id_number')}}">
                        @error('id_number')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Profile Picture</label>
                        <div class="custom-file">
                            <input type="file"
                                class="custom-file-input file @error('profile_picture') is-invalid @enderror"
                                id="customFile" accept="image/*" name="profile_picture">
                            @error('profile_picture')
                            <div class="invalid-feedback">
                                {{$message}}
                            </div>
                            @enderror
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="https://via.placeholder.com/400" class="img-fluid" id="preview" alt="Image Preview"
                        style="width: 400px; height: auto;">
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input type="text" name="first_name" id="first_name"
                            class="form-control @error('first_name') is-invalid @enderror"
                            value="{{old('first_name')}}">
                        @error('first_name')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="middle_name">Middle Name</label>
                        <input type="text" name="middle_name" id="middle_name"
                            class="form-control @error('middle_name') is-invalid @enderror"
                            value="{{old('middle_name')}}">
                        @error('middle_name')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input type="text" name="last_name" id="last_name"
                            class="form-control @error('last_name') is-invalid @enderror" value="{{old('last_name')}}">
                        @error('last_name')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="college">College</label>
                        <select name="college" id="college" class="form-control form-control-md">
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="course">Course</label>
                        <select name="course" id="course" class="form-control form-control-md">
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="year_level">Year Level</label>
                        <select class="form-control" name="year_level" id="year_level">
                            <option value="1" {{old('year_level') == '1'? 'selected':null}}>1</option>
                            <option value="2" {{old('year_level') == '2'? 'selected':null}}>2</option>
                            <option value="3" {{old('year_level') == '3'? 'selected':null}}>3</option>
                            <option value="4" {{old('year_level') == '4'? 'selected':null}}>4</option>
                            <option value="5" {{old('year_level') == '5'? 'selected':null}}>5</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="contact_number">Contact Number</label>
                        <input type="number" name="contact_number" id="contact_number"
                            class="form-control @error('contact_number') is-invalid @enderror"
                            value="{{old('contact_number')}}">
                        @error('contact_number')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="guardian_contact_number">Guardian Contact Number</label>
                        <input type="number" name="guardian_contact_number" id="guardian_contact_number"
                            class="form-control @error('guardian_contact_number') is-invalid @enderror"
                            value="{{old('guardian_contact_number')}}">
                        @error('guardian_contact_number')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="umak_email">Umak Email</label>
                        <input type="text" name="umak_email" id="umak_email"
                            class="form-control @error('umak_email') is-invalid @enderror"
                            value="{{old('umak_email')}}">
                        @error('umak_email')
                        <div class="invalid-feedback">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('js')
<script>
    $(document).ready(function() {

        $('#college').ready(getColleges()).change(function () {
            let val = $(this).val();
            getCourses(val);
        });
        $('input[type="file"]').change(function(e) {
            var fileName = e.target.files[0].name;

            var reader = new FileReader();
            reader.onload = function(e) {
                // get loaded data and render thumbnail.
                document.getElementById("preview").src = e.target.result;
            };
            // read the image file as a data URL.
            reader.readAsDataURL(this.files[0]);
        });
    });

    function getColleges(){
        $.get({
            url: "{{route('colleges.all')}}",
            success: function (data) {
                $.each(data, function (index, val) {
                    $('#college').append($('<option>').text(val.name).val(val.code));
                });
            }, 
            complete: function () {
                getCourses($('#college').val());
            }
        });
    }

    function getCourses(code) {
        let url = "{{route('api.courses.get', ['code' => ':code'])}}"; 
        $.get({
            url: url.replace(':code', code),
            success: function (data) {
                let course = $('#course');
                course.children().remove();
                $.each(data, (index, val) => {
                    course.append($('<option>').text(val.name).val(val.name));
                });
            }
        });
    }
</script>
@endsection

resources/views/students/profiles/profiles_index.blade.php
@extends('layouts.admin')

@section('content')
<!-- Basic Card Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Students / Profiles</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-sm nowrap" id="table" style="width:100%"></table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="importModal" tabindex="-1" role="dialog" aria-labelledby="importModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="importModalLabel">Import File</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('profiles.import') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="customFile" name="file" required
                            accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Import</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="SMSModal" tabindex="-1" role="dialog" aria-labelledby="SMSModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="SMSModalLabel">SMS Modal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="SMSForm" action="{{ route('globe.send') }}" method="post">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="address">Receiver Number: </label>
                        <input type="text" name="address" id="address" class="form-control" readonly>
                    </div>
                    <div class="form-group">
                        <label for="message">Message</label>
                        <textarea name="message" id="message" class="form-control"></textarea>
                        <small class="form-text text-muted">160 Characters only</small>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('js')
<script>
    $(document).ready(function () {
        let table = $('#table').DataTable({
            scrollX: true,
            ajax: {
                url: "/api/profiles/all",
                dataSrc: ''
            },
            fixedColumns: {
                leftColumns:0,
                rightColumns: 1
            },
            columns: [
                {data: 'id_number', title: 'Student Number'},
                {data: 'first_name', title: 'First Name'},
                {data: 'middle_name', title: 'Middle Name'},
                {data: 'last_name', title: 'Last Name'},
                {data: 'college', title: 'College'},
                // {data: 'course', title: 'Course'},
                {data: 'year_level', title: 'Year Level'},
                // {data: 'contact_number', title: 'Contact Number'},
                {data: 'umak_email', title: 'Umak Email'},
                // {
                //     data: 'status', title: 'Status', render: d => {
                //         return `<p class="badge badge-pill badge-${d == 'Expelled'?'danger':'success'} rounded-pill">${d}</p>`;
                //     }
                // },
                {
                    data: null, title: 'Action', render: d => {
                    let show = '{{route("profiles.show", ":id")}}';
                    let v    = '{{route("violations.show", ":id")}}';
                    let l    = '{{route("logs.show", ":id")}}'
                    return `<a class="btn btn-info btn-sm rounded-pill ml-1" href=${show.replace(":id", d.id_number)}><i class="fas fa-eye fa-sm"></i> View</a>` +
                    `<a class="btn btn-info btn-sm rounded-pill ml-1" href=${v.replace(":id", d.id_number)}><i class="fas fa-list fa-sm"></i> Violations</a>` +
                    `<a class="btn btn-success btn-sm rounded-pill ml-1" href=${l.replace(":id", d.id_number)}> Logs</a>`
                    // `<a class="btn btn-warning btn-sm rounded-pill ml-1" href="#"><i class="fas fa-pencil-alt"></i> Edit</a>` +
                    // `<button type="button" class="btn btn-success btn-sm rounded-pill ml-1" data-number=${d.contact_number} data-toggle="modal" data-target="#SMSModal"><i class="fas fa-envelope"></i> SMS</button>`;
                    }
                },
            ],
            dom: 'lBfrtip',
            buttons: [
                {
                    text: '<i class="fas fa-eye"></i> All',
                    className: 'btn btn-sm btn-warning mx-1 rounded-pill',
                    action: function (){
                        table.ajax.url("/api/profiles/all");
                        table.ajax.reload();
                    }
                },
                {
                    text: '<i class="fas fa-eye"></i> With Violations',
                    className: 'btn btn-sm btn-warning mx-1 rounded-pill',
                    action: function (){
                        table.ajax.url("/api/profiles/violations");
                        table.ajax.reload();
                    }
                },
                {
                    text: '<i class="fas fa-plus"></i> Add Student',
                    className: 'btn btn-sm btn-success mx-1 rounded-pill',
                    action: function (){
                        window.location.href = "{{route('profiles.create')}}"
                    }
                },
                {
                    text: '<i class="fas fa-file-import"></i> Import',
                    className: 'btn btn-sm btn-success mx-1 rounded-pill',
                    action: function () {
                        $('#importModal').modal('show');
                    }
                },
                // Printing
                // {
                //     text: '<i class="fas fa-print"></i> Print',
                //     extend: 'print',
                //     className: 'btn btn-success mx-1 rounded-pill'
                // },
                // {
                //     text: '<i class="fas fa-file-csv"></i> CSV',
                //     extend: 'csv',
                //     className: 'btn btn-success mx-1 rounded-pill'
                // },
                // {
                //     text: '<i class="fas fa-file-pdf"></i> PDF',
                //     extend: 'pdf',
                //     className: 'btn btn-success mx-1 rounded-pill'
                // },
            ],
        });

        $('#SMSModal').on('show.bs.modal', function (e) {
            let number = $(e.relatedTarget).data('number');
            $('#address').val(number);
        }).on('hide.bs.modal', function (e) {
            $('#address').val('');
        });

        $('#SMSForm').on('submit', function (e) {
            e.preventDefault();
            let formData = $(this).serializeArray();
            $.ajax({
                url: "{{route('globe.send')}}",
                type: "post",
                data: formData,
                complete: (j, s) => {
                    console.log({"data": j, "status": s});
                    if(s == "success"){
                        alertify.success(j.responseJSON.message);
                    }else {
                        alertify.error(j.responseJSON.message);
                    }
                }
            });
            $('#SMSModal').modal('hide');
        });
    });
</script>
@endsection